// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// DoSomething provides a mock function with given fields:
func (_m *MockService) DoSomething() (json.RawMessage, error) {
	ret := _m.Called()

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_DoSomething_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoSomething'
type MockService_DoSomething_Call struct {
	*mock.Call
}

// DoSomething is a helper method to define mock.On call
func (_e *MockService_Expecter) DoSomething() *MockService_DoSomething_Call {
	return &MockService_DoSomething_Call{Call: _e.mock.On("DoSomething")}
}

func (_c *MockService_DoSomething_Call) Run(run func()) *MockService_DoSomething_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_DoSomething_Call) Return(_a0 json.RawMessage, _a1 error) *MockService_DoSomething_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_DoSomething_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockService_DoSomething_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
